export type OutboxEntry = { id: string; createdAt: number; url: string; body: unknown; method: "POST" };
const DB = "inspection-assist-outbox"; const STORE = "requests";
function openDb(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const request = indexedDB.open(DB, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE, { keyPath: "id" }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
export async function enqueue(entry: Omit<OutboxEntry, "id" | "createdAt">) { const db = await openDb(); const value = { ...entry, id: crypto.randomUUID(), createdAt: Date.now() }; await new Promise<void>((resolve, reject) => { const tx = db.transaction(STORE, "readwrite"); tx.objectStore(STORE).add(value); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); return value; }
export async function countPending() { const db = await openDb(); return new Promise<number>((resolve, reject) => { const tx = db.transaction(STORE, "readonly"); const req = tx.objectStore(STORE).count(); req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error); }); }
let flushing = false;
export async function pendingInfo() { const db = await openDb(); return new Promise<{ count: number; oldestAt?: number }>((resolve, reject) => { const tx = db.transaction(STORE, "readonly"); const req = tx.objectStore(STORE).getAll(); req.onsuccess = () => { const entries = (req.result as OutboxEntry[]).sort((a, b) => a.createdAt - b.createdAt); resolve({ count: entries.length, oldestAt: entries[0]?.createdAt }); }; req.onerror = () => reject(req.error); }); }
export async function flushOutbox() { if (flushing) return { sent: 0, blocked: false }; flushing = true; try { const db = await openDb(); const entries = await new Promise<OutboxEntry[]>((resolve, reject) => { const tx = db.transaction(STORE, "readonly"); const req = tx.objectStore(STORE).getAll(); req.onsuccess = () => resolve((req.result as OutboxEntry[]).sort((a, b) => a.createdAt - b.createdAt)); req.onerror = () => reject(req.error); }); let sent = 0; for (const entry of entries) { let response: Response; try { response = await fetch(entry.url, { method: entry.method, headers: { "content-type": "application/json" }, body: JSON.stringify(entry.body) }); } catch { break; } if (!response.ok) break; await new Promise<void>((resolve, reject) => { const tx = db.transaction(STORE, "readwrite"); tx.objectStore(STORE).delete(entry.id); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); sent++; } return { sent, blocked: sent < entries.length }; } finally { flushing = false; } }
export const shouldRemoveAfterResponse = (status: number) => status >= 200 && status < 300;
